services:
        opal:
                image: obiba/opal:latest
                #image: obiba/opal:test
                ports:
                        - "8880:8080"
                links:
                        - mongo
                        - mysqldata
                        - mariadbdata
                        - postgresdata
                        - rock
                environment:
                        - OPAL_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - MONGO_USER=root
                        - MONGO_PASSWORD=example
                        - MYSQLDATA_DATABASE=opal
                        - MYSQLDATA_HOST=mysqldata
                        - MYSQLDATA_USER=opal
                        - MYSQLDATA_PASSWORD=password
                        - MARIADBDATA_DATABASE=opal
                        - MARIADBDATA_HOST=mariadbdata
                        - MARIADBDATA_USER=opal
                        - MARIADBDATA_PASSWORD=password
                        - POSTGRESDATA_DATABASE=opal
                        - POSTGRESDATA_HOST=postgresdata
                        - POSTGRESDATA_USER=opal
                        - POSTGRESDATA_PASSWORD=password
                        - ROCK_HOSTS=rock:8085
                volumes:
                        - /tmp/test-opal:/srv
        mongo:
                image: mongo
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_ROOT_PASSWORD=example
        mysqldata:
                image: mysql
                environment:
                        - MYSQL_DATABASE=opal
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_USER=opal
                        - MYSQL_PASSWORD=password
        mariadbdata:
                image: mariadb
                environment:
                        - MYSQL_DATABASE=opal
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_USER=opal
                        - MYSQL_PASSWORD=password
        postgresdata:
                image: postgres
                environment:
                        - POSTGRES_DB=opal
                        - POSTGRES_USER=opal
                        - POSTGRES_PASSWORD=password
        rock:
                image: obiba/rock:latest
                volumes:
                        - /tmp/rock:/srv
